name: "Release-PR Pipeline"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  release:
    name: Release WebGoat
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    environment:
      name: release
    steps:
      - uses: actions/checkout@v4
 
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          architecture: x64
 
      - name: Cache Maven packages
        uses: actions/cache@v3.3.2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
 
      - name: "Set labels for ${{ github.ref }}"
        run: |
          echo "WEBGOAT_TAG_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          WEBGOAT_MAVEN_VERSION=${{ github.ref_name }}
          echo "WEBGOAT_MAVEN_VERSION=${WEBGOAT_MAVEN_VERSION:1}" >> $GITHUB_ENV
      - name: Build with Maven
        run: |
          mvn --no-transfer-progress versions:set -DnewVersion=${{ env.WEBGOAT_MAVEN_VERSION }}
          mvn --no-transfer-progress install -DskipTests
 
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3
      - name: "Build WebGoat Docker"
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./
          file: ./Dockerfile
          push: false
          load: true
          tags: |
            webgoat/webgoat:${{ env.WEBGOAT_TAG_VERSION }}
            webgoat/webgoat:latest
          build-args: |
            webgoat_version=${{ env.WEBGOAT_MAVEN_VERSION }}
 
      - name: Mend CLI Scan
        env:
          MEND_EMAIL: ${{secrets.MEND_EMAIL}}
          MEND_USER_KEY: ${{secrets.MEND_USER_KEY}}
          MEND_URL: https://saas.mend.io
        run: |
          echo Downloading Mend CLI
          curl -LJO https://downloads.mend.io/production/unified/latest/linux_amd64/mend && chmod +x mend
          echo "Start Mend image scan"
          ./mend image webgoat/webgoat:${{ env.WEBGOAT_TAG_VERSION }}

  pull_request:
    name: Pull Request WebGoat
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
 
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          architecture: x64
 
      - name: Cache Maven packages
        uses: actions/cache@v3.3.2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn --no-transfer-progress install -DskipTests